### ISSUE TITLE
Deccan delight-tamilgun

### ISSUE THREAD

**Issue by rubanrex** [reasonsrepo/repository.reasonsrepo#12]
Hi,

Tamildbox.tips is not working. Could you please change it to current website, which is tamildbox.top

**Comment by Gujal00** [comment]
Does anybody maintain Deccan Delight in this repo?
;-)

**Comment by rubanrex** [comment]
Gujal, you're back!!!

**Comment by reasonsrepo** [comment]
As Gujal is back, I will no longer be maintaining the addon, love ya @Gujal00
