### ISSUE TITLE
What is the url now for installing the repo

### ISSUE THREAD

**Issue by synraj** [reasonsrepo/repository.reasonsrepo#16]
Hi,
I have been using reasonsrepo.ml and when i checked after a long time i could not see the link working. I see some details on this for the repository on github. what will be the url to give on the add source in kodi

**Comment by cybrain29** [comment]
You need to install it using the Git browser from Indigo. Go to 'Search by Github repository title' for 'reasonsrepo' and install 'repository.reasonsrepo-1.0.1.zip'. Restart Kodi and then install addon using  Settings-> Addons-> Install from repository.

**Comment by reddit-reaper** [comment]
@reasonsrepo i recommend you do what we did for a4k repo. you can see an example here :) no need for a website you can use github to do it

https://github.com/a4k-openproject/a4k-openproject.github.io

which points to this url for kodi file manager

https://a4k-openproject.github.io/

**Comment by reasonsrepo** [comment]
@reddit-reaper ahh yep thanks a lot for the suggestion, will try it in a bit

**Comment by reasonsrepo** [comment]
@synraj @cybrain29 the new repo is http://reasonsrepos.000webhostapp.com/repo/

**Comment by sresam89** [comment]
@reasonsrepo The link is down again "http://reasonsrepos.000webhostapp.com/repo/"
