### ISSUE TITLE
Movierulz Plugin Update

### ISSUE THREAD

**Issue by geonathan69** [reasonsrepo/repository.reasonsrepo#3]
Please update link to https://movierulz.ht, as the  .pe is not working now

**Comment by reasonsrepo** [comment]
Okay thanks for letting me know

**Comment by raamch** [comment]
Hi, this plugin is not working on kodi19. it would be nice to see it working on kodi 19.

**Comment by mrblrao** [comment]
what is latest repository for movieurlz in kodi-19
regards
MRBLRAO
mrblrao@gmail.com
