### ISSUE TITLE
Einthusan Skips 10-15 secs video every minute on (v18) Leia

### ISSUE THREAD

**Issue by selva005** [reasonsrepo/repository.reasonsrepo#7]
I am not sure if this has to be addressed in the Add-on.

Problem:
Einthusan video plays but it skips few seconds of video randomly. This causes a very unpleasant viewing experience.

I am not sure if there is update required on the Add-on for the new kodi version.

-Selva

**Comment by sathish804** [comment]
I also see the same behavior on Leia.

Dear developer kindly.look into this issue.

**Comment by reasonsrepo** [comment]
Most likely caused by slow internet, or congested servers
