### ISSUE TITLE
Einthusan addon 1.4.5 not working with Kodi Krypton 17.6 version

### ISSUE THREAD

**Issue by Madhuri0789** [reasonsrepo/repository.reasonsrepo#8]
Hi,

When I install the latest add on 1.4.5 for Einthusan on Kodi Krypton 17.6, it does not open any titles, when browsed in 2019, 2018 in any of the Hindi, Telugu or any other folders. It straight away gives an error check the log info.

I believe Einthusan.tv link everywhere in default.py file is causing the issue, and replacing it with einthusan.com might fix it.

Upon further investigation, I found that einthusan.tv link is down in the web browser too, but einthusan.com link works fine.

Please fix this issue and push the new update.

Thanks in advance.

Madhu.

**Comment by me30122** [comment]
It’s also not working in kodi 18.2

**Comment by reasonsrepo** [comment]
Fixed

**Comment by Madhuri0789** [comment]
> Fixed

Has this been tested? The menu opens up, movies names show up, but movie doesn't play.
